# Generated by Django 2.2.3 on 2019-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionElectivas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44)),
                ('password', models.CharField(max_length=44)),
            ],
        ),
    ]
